controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # CAMBIATO NOME E TIPO: Usiamo un controller di posizione diretta
    chef_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

chef_position_controller:
  ros__parameters:
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
      - joint_a7
    
    # Non servono PID complessi per il JointGroupPositionController in simulazione
    # Gazebo userà la modalità servo posizione diretta